name: Deploy to EC2

on:
  push:
    branches:
      - none

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ching-portfolio .

      - name: Save Docker image to tarball
        run: docker save -o ching-portfolio.tar ching-portfolio
        
      - name: Set permissions on tar file
        run: chmod +r ching-portfolio.tar
        
      - name: Transfer Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ching-portfolio.tar
          target: /home/ubuntu/app

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |            
            docker rm -f ching-portfolio || true
            docker rmi ching-portfolio || true
            docker load -i /home/ubuntu/app/ching-portfolio.tar
            docker run -d --name ching-portfolio -p 3000:3000 ching-portfolio
