name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Dockerfile to EC2
        run: scp -r Dockerfile ${{ secrets.EC2_PUBLIC_IP }}:~/ching-portfolio-app
        
      - name: Copy app files to EC2
        run: scp -r . ${{ secrets.EC2_PUBLIC_IP }}:~/ching-portfolio-app
        
      - name: SSH into EC2 and build Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            cd ~/ching-portfolio-app
            docker build -t ching-portfolio-app .

      - name: SSH into EC2 and run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            docker stop my-nextjs-app || true
            docker rm my-nextjs-app || true
            docker run -d -p 3000:3000 --name ching-portfolio-app ching-portfolio-app:latest
