
name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ching-portfolio .

      - name: Set permissions for private key
        run: chmod 600 ${{ secrets.EC2_SSH_KEY }}
        
      - name: SCP Dockerfile to EC2 instance
        run: scp -i ${{ secrets.EC2_SSH_KEY }} ching-portfolio ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/var/www/ching-portfolio-app

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/ching-portfolio-app
            docker run -d -p 3000:3000 ching-portfolio
