name: Test SSH connection to EC2

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22  # Adjust the port if necessary
          script: |
            echo "SSH connection successful!"
